package paspo.id.ssoprovider.client

import android.app.Activity
import android.content.ActivityNotFoundException
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import androidx.activity.ComponentActivity
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.net.toUri
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import paspo.id.ssoprovider.client.internal.EncryptionProcessor
import paspo.id.ssoprovider.client.internal.RawResult
import paspo.id.ssoprovider.client.internal.ReferralManager
import paspo.id.ssoprovider.shared.models.PaspoClientError
import paspo.id.ssoprovider.shared.models.PaspoScope
import paspo.id.ssoprovider.shared.models.PaspoSsoConstants
import paspo.id.ssoprovider.shared.models.PaspoSsoProviderException
import paspo.id.ssoprovider.shared.models.PaspoSsoResult
import paspo.id.ssoprovider.shared.models.internal.EncryptedEnvelope
import java.util.UUID
import kotlin.coroutines.resume

/**
 * Entry point of the PaspoID SDK: authenticates the user via the Paspo app.
 *
 * The instance keeps a reference to [activity]; create it per screen and do not store it
 * in objects that outlive the activity (view models, singletons).
 *
 * @param activity Activity that launches the Paspo consent screen and receives its result.
 */
public class PaspoID(
    private val activity: ComponentActivity
) {
    public companion object {
        /**
         * Intent action the Paspo app uses to launch your application when the user starts
         * sign-in from the Paspo side.
         *
         * To support this entry point, declare an intent-filter with this action on the
         * activity that hosts your sign-in flow and start the flow when the activity is
         * launched with it. Supporting the action is optional: the SDK works without it.
         */
        public const val ACTION_SIGN_IN: String = PaspoSsoConstants.ACTION_AUTH
    }

    private val json by lazy { Json { ignoreUnknownKeys = true } }
    private val encryptionProcessor by lazy { EncryptionProcessor(json) }
    private val appContext: Context by lazy { activity.applicationContext }

    private val referralManager: ReferralManager by lazy { ReferralManager(appContext) }

    /**
     * Runs the SSO flow: opens the Paspo consent screen and returns its outcome.
     *
     * Call from a coroutine bound to the activity (e.g. `lifecycleScope`) while the activity
     * is resumed, one flow at a time: a new call resets the state of the previous one.
     * All outcomes, including cancellation and missing Paspo app, are reported via
     * [PaspoAuthResult]; the method does not throw.
     *
     * If Paspo is not installed, the SDK opens its Play Store page and returns
     * [PaspoAuthResult.NotInstalled].
     *
     * @param scope Profile data to request from the user.
     * @param nonce One-time anti-replay value generated by your backend for this attempt.
     * @return Outcome of the flow; on [PaspoAuthResult.Success] pass
     * [PaspoAuthResult.Success.authCode] to your backend.
     */
    public suspend fun authenticate(
        scope: PaspoScope,
        nonce: String,
    ): PaspoAuthResult {
        if (!checkInstallation()) {
            referralManager.saveReferralNonce(nonce)
            openPlayStore()
            return PaspoAuthResult.NotInstalled
        }

        cleanup()

        val keyPair = withContext(Dispatchers.Default) { encryptionProcessor.generateKeyPair() }

        val referralNonce = referralManager.getReferralNonce()
        val intent = Intent(PaspoSsoConstants.ACTION_AUTH).apply {
            setPackage(PaspoSsoConstants.TARGET_PACKAGE)
            putExtra(PaspoSsoConstants.EXTRA_CLIENT_PUBLIC_KEY, keyPair.publicKeyBytes.bytes)
            putExtra(PaspoSsoConstants.EXTRA_REQUEST_NONCE, nonce)
            putExtra(PaspoSsoConstants.EXTRA_SCOPE, scope.key)
            referralNonce?.let { putExtra(PaspoSsoConstants.EXTRA_REFERRAL_NONCE, it) }
        }

        val rawResult = launchForResult(intent)
        return withContext(Dispatchers.Default) { handleResult(rawResult) }
    }

    /**
     * Returns `true` if the Paspo app is installed.
     *
     * Optional: [authenticate] performs this check itself. Useful to adapt UI upfront,
     * e.g. the sign-in button label.
     */
    public suspend fun checkInstallation(): Boolean =
        withContext(Dispatchers.IO) {
            try {
                appContext.packageManager.getPackageInfo(PaspoSsoConstants.TARGET_PACKAGE, 0)
                true
            } catch (_: PackageManager.NameNotFoundException) {
                false
            }
        }

    /**
     * Destroys the ephemeral encryption keys of the current flow.
     *
     * Called automatically when the flow completes or fails; call manually only when
     * abandoning a flow midway (e.g. the user leaves the sign-in screen).
     */
    public fun cleanup(): Unit = encryptionProcessor.cleanup()

    private suspend fun launchForResult(intent: Intent): RawResult =
        withContext(Dispatchers.Main) {
            suspendCancellableCoroutine { continuation ->
                val registryKey = "paspo_sso_auth_${UUID.randomUUID()}"
                var launcher: ActivityResultLauncher<Intent>? = null

                launcher = activity.activityResultRegistry.register(
                    registryKey,
                    ActivityResultContracts.StartActivityForResult()
                ) { result ->
                    launcher?.unregister()
                    if (continuation.isActive) continuation.resume(RawResult(result.resultCode, result.data))
                }

                continuation.invokeOnCancellation { launcher.unregister() }

                launcher.launch(intent)
            }
        }

    private fun handleResult(rawResult: RawResult): PaspoAuthResult {
        if (rawResult.resultCode == Activity.RESULT_CANCELED) {
            cleanup()
            return PaspoAuthResult.Cancelled
        }

        val data = rawResult.data ?: return failure(PaspoClientError.INVALID_REQUEST, "No data in response")

        val errorCode = data.getIntExtra(PaspoSsoConstants.EXTRA_ERROR_CODE, -1)
        if (errorCode != -1) {
            val error = PaspoClientError.fromCode(errorCode)
            return if (error == PaspoClientError.CANCELLED) {
                cleanup()
                PaspoAuthResult.Cancelled
            } else {
                failure(error, null)
            }
        }

        val responseBytes = data.getByteArrayExtra(PaspoSsoConstants.EXTRA_ENCRYPTED_RESPONSE)
            ?: return failure(PaspoClientError.INVALID_REQUEST, "No encrypted response")

        return try {
            val envelope = json.decodeFromString<EncryptedEnvelope>(responseBytes.decodeToString())
            when (val result = encryptionProcessor.decryptAuthResult(envelope)) {
                is PaspoSsoResult.Success -> PaspoAuthResult.Success(authCode = result.nonce)
                is PaspoSsoResult.Failure -> failure(PaspoClientError.fromCode(result.errorCode), null)
            }
        } catch (e: PaspoSsoProviderException) {
            failure(e.code, e.message)
        } catch (e: Exception) {
            failure(PaspoClientError.CRYPTO_ERROR, e.message ?: "Decryption failed")
        }
    }

    private fun failure(
        error: PaspoClientError,
        message: String?,
    ): PaspoAuthResult.Failure {
        cleanup()
        return PaspoAuthResult.Failure(error, message)
    }

    private fun openPlayStore() {
        try {
            val uri = "market://details?id=${PaspoSsoConstants.TARGET_PACKAGE}".toUri()
            activity.startActivity(Intent(Intent.ACTION_VIEW, uri).apply { addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) })
        } catch (_: ActivityNotFoundException) {
            val webUri = "https://play.google.com/store/apps/details?id=${PaspoSsoConstants.TARGET_PACKAGE}".toUri()
            activity.startActivity(Intent(Intent.ACTION_VIEW, webUri).apply { addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) })
        }
    }
}
